modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Libre-Computers/LibreLanguages/issues"
license = "MIT"

[[mods]]
modId = "ll"
version = "${file.jarVersion}"
displayName = "Libre Languages"
authors = "The Realm 18 Studios"
description = '''
Libre Languages Addon.
'''

[[dependencies.ll]]
modId = "forge"
mandatory = true
versionRange = "[40.1.68,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ll]]
modId = "minecraft"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ll]]
modId = "oc2"
mandatory = true
versionRange = "[1.1.0,)"
side = "BOTH"
ordering = "AFTER"
